services:
  # Serviço do Banco de Dados MySQL
  mysql_db:
    image: mysql:8.0
    container_name: itau-mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: itau_challenge_db
    ports:
      - "3306:3306" # Expõe a porta do banco para o seu localhost
    volumes:
      - mysql_data:/var/lib/mysql

  # Serviço da sua API .NET
  itau_api:
    container_name: itau-api
    build:
      context: ..
      dockerfile: deployment/Dockerfile 
    restart: unless-stopped
    ports:
      - "8080:8080" # Mapeia a porta 8080 do container para a 8080 do seu localhost
      - "8081:8081" # Porta HTTPS, se configurada
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      # A string de conexão aponta para o nome do serviço do banco de dados
      - ConnectionStrings__DefaultConnection=Server=mysql_db;Port=3306;Database=itau_challenge_db;Uid=root;Pwd=${DB_PASSWORD}
    depends_on:
      - mysql_db # Garante que o banco de dados inicie antes da API

volumes:
  mysql_data:
